trigger:
- main  # or your desired branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  zapImage: 'ghcr.io/zaproxy/zaproxy:stable'
  targetUrl: 'https://www.hackerrank.com/'  # Replace with your actual target URL
  reportName: 'zap_report.html'

steps:
- task: Bash@3
  displayName: 'Run OWASP ZAP Baseline Scan'
  inputs:
    targetType: 'inline'
    script: |
      echo "Pulling ZAP Docker image from GHCR..."
      docker pull ${{ variables.zapImage }}

      echo "Creating output directory..."
      mkdir -p $(Build.ArtifactStagingDirectory)/zap-reports

      echo "Running ZAP baseline scan..."
      docker run --rm \
        -v $(Build.ArtifactStagingDirectory)/zap-reports:/zap/wrk \
        ${{ variables.zapImage }} \
        zap-baseline.py \
          -t ${{ variables.targetUrl }} \
          -r ${{ variables.reportName }}

- task: PublishBuildArtifacts@1
  displayName: 'Publish ZAP Report'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/zap-reports'
    ArtifactName: 'ZAP-Report'
    publishLocation: 'Container'
