trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'  # or 'windows-latest'

steps:
  - script: |
      docker pull owasp/zap2docker-stable
    displayName: 'Pull OWASP ZAP Docker Image'

  - script: |
      docker run --rm -v $(System.DefaultWorkingDirectory):/zap/wrk owasp/zap2docker-stable \
        zap-baseline.py \
        -t https://www.hackerrank.com/ \
        -r zap-report.html \
        -x zap-report.xml
    displayName: 'Run ZAP Baseline Scan'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/zap-report.html'
      artifactName: 'ZAP_Report'
    displayName: 'Publish ZAP HTML Report'

  # Optional: Fail the pipeline if high-risk vulnerabilities are found
  - script: |
      if grep -q "High" $(System.DefaultWorkingDirectory)/zap-report.html; then
        echo "##vso[task.logissue type=error]High-risk vulnerabilities detected!"
        exit 1
      fi
    displayName: 'Check for High-Risk Vulnerabilities'