trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  zapVersion: '2.16.1'
  zapFolder: 'zap'
  reportName: 'zap_report.html'
  targetUrl: 'https://example.com'  # 🔁 Replace with your site

jobs:
- job: ZapScan
  displayName: 'Run OWASP ZAP Baseline Scan on Linux'
  steps:
    - checkout: none

    - task: Bash@3
      displayName: 'Download and Extract OWASP ZAP'
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p ${{ variables.zapFolder }}
          curl -L https://github.com/zaproxy/zaproxy/releases/download/v${{ variables.zapVersion }}/ZAP_${{ variables.zapVersion }}_Linux.tar.gz -o zap.tar.gz
          tar -xzf zap.tar.gz -C ${{ variables.zapFolder }}

    - task: Bash@3
      displayName: 'Run ZAP Baseline Scan'
      inputs:
        targetType: 'inline'
        script: |
          ZAP_JAR=$(find ${{ variables.zapFolder }} -name "zap-baseline.jar")
          java -jar "$ZAP_JAR" \
            -t ${{ variables.targetUrl }} \
            -r ${{ variables.reportName }} \
            -I

    - task: PublishPipelineArtifact@1
      displayName: 'Publish ZAP Scan Report'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/${{ variables.reportName }}'
        artifactName: 'ZAP-Scan-Report'
